name: amplifications
favicon: null
layout_spectrum: 0.9972791348118335
typography_spectrum: 0.014756252057850361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3115163999609649
  lightness: 0.49652839358896017
  saturation: 0.3592675500549376
  rhythmicContrast: 0.46692665573209524
purpose: []
